source = "";
_type = "";
damage = 0;
mass = 0;
current_horizontal_speed = 0;
current_vertical_speed = 0;
onHit = [];
collide_object = false;
_incorporeal = false;
_explosion = noone;
_harm = true;
physics = false;
event_user(0);